FROM envoyproxy/envoy-dev:latest

COPY ./envoy-backend.yaml /etc/envoy.yaml
COPY ./certs/ca.crt /certs/cacert.pem
COPY ./certs/proxy-splunk-backend.home.local.crt /certs/servercert.pem
COPY ./certs/proxy.key /certs/serverkey.pem

RUN chmod go+r /etc/envoy.yaml /certs/cacert.pem /certs/serverkey.pem /certs/servercert.pem
CMD ["/usr/local/bin/envoy", "-c /etc/envoy.yaml", "-l", "debug"]
