FROM envoyproxy/envoy-dev:latest

COPY ./envoy-frontend.yaml /etc/envoy.yaml
COPY ./certs/ca.crt /certs/cacert.pem
COPY ./certs/proxy-splunk-frontend.home.local.crt /certs/clientcert.pem
COPY ./certs/proxy.key /certs/clientkey.pem

RUN chmod go+r /etc/envoy.yaml /certs/cacert.pem /certs/clientkey.pem /certs/clientcert.pem
CMD ["/usr/local/bin/envoy", "-c /etc/envoy.yaml", "-l", "debug"]
